import React from 'react'

function Termsofcondition() {
  return (
    <div>
      <p>Disclaimer: In case of any discrepancy or difference, the English version will take precedence over the translation</p>
      <h1> <b className='congo'>Congo</b><b>kart Terms of Use</b></h1>
      <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
      <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name \[www.congokart.com\] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)</p>
      <p>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with congokart Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with congokart.</p>
      <p>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Congokart allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Congokart Internet Private Limited.</p>
      <p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Congokart Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.</p>
      <h1>Membership Eligibility</h1>
      <p>Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent or legal guardian.</p>
      <h1>Your Account and Registration Obligations</h1>
      <p>If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.</p>
      <h1>Platform for Transaction and Communication</h1>
      <p>
        The Platform enables the Buyer and Seller to transact on the Platform. . Flipkart is not and cannot be a party to or control in any manner any transaction between the Platform's Users.
      </p>
      
        <ul>
          <li>
          All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Flipkart does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Flipkart.
          </li>
       
         <li>Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.
      </li>
      <li>Flipkart does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. Flipkart does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. Flipkart accepts no liability for any errors or omissions, whether on behalf of itself or third parties.</li>
      <li>At no time shall Flipkart hold any right, title or interest over the products nor shall Flipkart have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Flipkart is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.</li>
      <li>The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Flipkart is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.</li>
       </ul>
    </div>
  )
}

export default Termsofcondition
